apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: kube-dns
  labels:
    team: frontend
spec:
  namespaceSelector:
    any: true
    matchNames:
      - kube-system
  selector:
    matchLabels:
      k8s-app: kube-dns
      kubernetes.io/cluster-service: "true"
      kubernetes.io/name: KubeDNS
  endpoints:
    - port: metrics
