apiVersion: v1
kind: Service
metadata:
  labels:
    k8s-app: etcd
  name: etcd
  namespace: monitoring
spec:
  clusterIP: None
  ports:
    - name: https-metrics
      port: 2379
      protocol: TCP
      targetPort: 2379
  sessionAffinity: None
  type: ClusterIP
