apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: grafana-ingress
  namespace: monitoring
spec:
  rules:
    - host: grafana.talcoding.com
      http:
        paths:
          - backend:
              serviceName: grafana
              servicePort: 3000