apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: controller-manager
  labels:
    team: frontend
spec:
  namespaceSelector:
    any: true
    matchNames:
      - kube-system
  selector:
    matchLabels:
      app: controller-manager
  endpoints:
    - port: http
