apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: apiserver-monitor
  labels:
    team: frontend
spec:
  namespaceSelector:
    any: true
    matchNames:
      - default
  selector:
    matchLabels:
      component: apiserver
      provider: kubernetes
  endpoints:
    - port: https
      scheme: https
      tlsConfig:
        caFile: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
      bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token

